name: Basic Lint and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
